ext {
    springBootVersion = '3.4.1'
    lombokVersion = '1.18.30'
}

buildscript {

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:3.4.1"
        classpath "io.spring.gradle:dependency-management-plugin:1.1.7"
    }
}

allprojects {
    apply plugin: 'java'

    group = 'org.example.fileservice'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }

    configurations {
        all {
            exclude group: 'commons-logging', module: 'commons-logging'
            exclude group: 'org.slf4j', module: 'slf4j-simple'
        }
    }
}

subprojects {
    java {
        sourceCompatibility = '17'
    }

    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'


    dependencies {
        implementation("org.springframework.boot:spring-boot-starter-web")
        implementation "org.springframework.boot:spring-boot-starter:${rootProject.springBootVersion}"
        testImplementation "org.springframework.boot:spring-boot-starter-test:${rootProject.springBootVersion}"

        implementation "org.springframework.boot:spring-boot-starter-actuator:${rootProject.springBootVersion}"

        compileOnly "org.projectlombok:lombok:${rootProject.lombokVersion}"
        testCompileOnly "org.projectlombok:lombok:${rootProject.lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${rootProject.lombokVersion}"
        testAnnotationProcessor "org.projectlombok:lombok:${rootProject.lombokVersion}"

        implementation 'org.springframework.boot:spring-boot-starter-security'
        implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
        implementation 'org.springframework.boot:spring-boot-starter-webflux'

        implementation 'org.springframework.boot:spring-boot-starter-validation'

        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.springframework.security:spring-security-test'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

//    test {
//        useJUnitPlatform()
//    }

    bootJar {
        enabled = true
        mainClass = 'org.example.fileservice.Application'
    }
}

// build jar
jar {
    def jars = configurations.runtimeClasspath.files.collect { "lib/$it.name" }

    manifest {
        attributes 'Main-Class': 'org.example.fileservice.Application',
                'Class-Path': jars.join(' ')
    }
}

tasks.register('copyCredentials', Copy) {
    from 'credentials.json'
    into "$buildDir"
}

tasks.register('copyAllDependencies', Copy) {
    from(configurations.runtimeClasspath.files)
    into("$buildDir/libs/lib")
}

jar.dependsOn copyAllDependencies
jar.dependsOn copyCredentials
